/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.intsuperior.vista1;



/**
 *
 * @author Daniel C
 */
public class frminicio extends javax.swing.JFrame {


    public frminicio() {
        initComponents();
    
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listagregar = new javax.swing.JMenuItem();
        editadocente = new javax.swing.JMenuItem();
        eliminadocente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        editarestudiante = new javax.swing.JMenuItem();
        eliminarestudiante = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema ");

        escritorio.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/User.png"))); // NOI18N
        jMenu1.setText("DOCENTE");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        listagregar.setText("Agregar");
        listagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagregarActionPerformed(evt);
            }
        });
        jMenu1.add(listagregar);

        editadocente.setText("Editar");
        editadocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editadocenteActionPerformed(evt);
            }
        });
        jMenu1.add(editadocente);

        eliminadocente.setText("Eliminar");
        eliminadocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminadocenteActionPerformed(evt);
            }
        });
        jMenu1.add(eliminadocente);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/User2.png"))); // NOI18N
        jMenu2.setText("ESTUDIANTE");

        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        editarestudiante.setText("Editar");
        editarestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarestudianteActionPerformed(evt);
            }
        });
        jMenu2.add(editarestudiante);

        eliminarestudiante.setText("Eliminar");
        eliminarestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarestudianteActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarestudiante);

        jMenuBar1.add(jMenu2);

        menusalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        menusalir.setText("Ayuda");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Acerca de ..");
        menusalir.add(jMenuItem1);

        jMenuBar1.add(menusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        escritorio.getAccessibleContext().setAccessibleParent(escritorio);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagregarActionPerformed
       frmdocente verdocente = new frmdocente ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(verdocente);
       verdocente.show();
    }//GEN-LAST:event_listagregarActionPerformed

    private void editadocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editadocenteActionPerformed
        frmeditardocente vereditardoce = new frmeditardocente ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(vereditardoce);
       vereditardoce.show();
    }//GEN-LAST:event_editadocenteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       frmestudiante verdocente = new frmestudiante ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(verdocente);
       verdocente.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
  
    }//GEN-LAST:event_menusalirActionPerformed

    private void eliminadocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminadocenteActionPerformed
        frmeliminardocente verelitardoce = new frmeliminardocente ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(verelitardoce);
       verelitardoce.show();
    }//GEN-LAST:event_eliminadocenteActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void editarestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarestudianteActionPerformed
         frmeditarestudiante verediest = new frmeditarestudiante ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(verediest );
       verediest .show();
    }//GEN-LAST:event_editarestudianteActionPerformed

    private void eliminarestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarestudianteActionPerformed
         frmeliminarestudiante vereliest = new frmeliminarestudiante ();
       escritorio.removeAll();
       escritorio.repaint();
       escritorio.add(vereliest);
       vereliest .show();
    }//GEN-LAST:event_eliminarestudianteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editadocente;
    private javax.swing.JMenuItem editarestudiante;
    private javax.swing.JMenuItem eliminadocente;
    private javax.swing.JMenuItem eliminarestudiante;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem listagregar;
    private javax.swing.JMenu menusalir;
    // End of variables declaration//GEN-END:variables
}
